### ISSUE TITLE
baichuan2 inference with vllm

### ISSUE THREAD

**Issue by AGI-player** [AniZpZ/AutoSmoothQuant#19]
Thanks for your great work, i wonder if baichuan2 quantized with AutoSmoothQuant can be inferenced with vllm now?

**Comment by AniZpZ** [comment]
you can export and save quantized param and model with autosmoothquant and inference with vllm(you need to add quantized baichuan model file to vllm)

**Comment by AGI-player** [comment]
> you can export and save quantized param and model with autosmoothquant and inference with vllm(you need to add quantized baichuan model file to vllm)

thanks~
