### ISSUE TITLE
Smoothquant for Phi2

### ISSUE THREAD

**Issue by ponytaill** [AniZpZ/AutoSmoothQuant#21]
Hi, thank you for your great work. I'm editing the code to implement Phi-2.  But I have some problems. Are you interested in helping me and judge my code? We can talk it on WeChat.

**Comment by ponytaill** [comment]
The ppl of the quantized phi2 is 50, which should be 7 correctly. Anyone can help me out?

**Comment by AniZpZ** [comment]
Try using per-token quantization config:
{
  "qkv": "per-token",
  "out": "per-token",
  "fc1": "per-token",
  "fc2": "per-token"
}

**Comment by ponytaill** [comment]
> Try using per-token quantization config: { "qkv": "per-token", "out": "per-token", "fc1": "per-token", "fc2": "per-token" }

Hi, thanks for your reply. Unfortunately, I found this config before. My ppl of 50 is exactly the result obtained after per-token quantization, and the ppl of original per-tensor is more than 100. Any ideas?

**Comment by ponytaill** [comment]
The good news is, after I change the weight quantization config to Per_channel, the ppl decrease to 40. The bad news is that it is still bad.

**Comment by ponytaill** [comment]
Ah, I finally figure it out. The reason is I forget to replace the final_layernorm in PhiModel class and use bias in MLP which is wrong. Now the ppl is 12. Looks fine.
